SELECT * FROM ALL_ORDER;

SELECT FIRST_NAME, LAST_NAME, DOB, EMAIL, PHONE
FROM CUSTOMER;

SELECT * FROM PRODUCT;

SELECT * 
FROM MANUFACTURER A
LEFT JOIN PRODUCT B
ON A.MANUFACTURER_ID = B.MANUFACTURER_ID;

SELECT * FROM PRODUCT
ORDER BY PRICE DESC;

SELECT A.ORDER_ID, C.PRODUCT_ID, C.PRODUCT_NAME
FROM ALL_ORDER A
JOIN ORDER_HAS_PRODUCTS B ON A.ORDER_ID = B.ORDER_ID
JOIN PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID
FETCH FIRST 10 ROWS ONLY;

SELECT DISTINCT *
FROM ALL_ORDER A
JOIN ORDER_HAS_PRODUCTS B ON A.ORDER_ID = B.ORDER_ID
JOIN PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID;    

SELECT A.ORDER_ID, count(C.PRODUCT_ID) AS PRODUCT
FROM ALL_ORDER A
JOIN ORDER_HAS_PRODUCTS B on A.ORDER_ID = B.ORDER_ID
JOIN PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID
GROUP BY 1
HAVING Price>10;

SELECT * FROM EMPLOYEE 
WHERE ZIPCODE IN (75252,75080,75010);

SELECT LENGTH(PRODUCT_NAME) FROM PRODUCT;

SELECT * FROM EMPLOYEE;
DELETE FROM EMPLOYEE WHERE EMPLOYEE_ID = 1000000;
SELECT * FROM EMPLOYEE;
ROLLBACK;

SELECT * FROM EMPLOYEE;
UPDATE EMPLOYEE SET City = 'Austin' WHERE EMPLOYEE_ID = 1000002;
Select * from EMPLOYEE;
ROLLBACK;

SELECT COUNT(DISTINCT A.ORDER_ID) AS ONLINE_ORDERS
FROM ALL_ORDER A
JOIN ONLINE_ORDER B 
ON A.ORDER_ID = B.ORDER_ID;

SELECT ORDER_ID, AVG(NO_OF_ITEMS) AS
FROM ALL_ORDER
GROUP BY 1;

SELECT CUSTOMER_ID, AVG(ORDER_ID) AS AVG_ONLINE_ORDER
FROM CUSTOMER A
JOIN ALL_ORDER B ON A.ORDER_ID=B.ORDER_ID
JOIN ONLINE_ORDER C ON B.ORDER_ID=C.ORDER_ID
GROUP BY 1;

SELECT SHIPMENT_STATUS, COUNT(DISTINCT ORDER_ID) AS orders 
FROM SHIPMENT A
JOIN ONLINE_ORDER B ON A.ORDER_ID=B.ORDER_ID
JOIN ALL_ORDER C ON B.Order_ID=C.ORDER_ID
GROUP BY 1;

SELECT CUSTOMER_ID, AVG(PAYMENT_ID) AS AVG_PAYMENTS
FROM CUSTOMER A
JOIN MEMBER B ON A.CUSTOMER_ID=B.CUSTOMER_ID
JOIN PAYMENT_INFO C ON B.MEMBERSHIP_NO=C.MEMBERSHIP_NO
GROUP BY 1;

SELECT A.CITY, COUNT(DISTINCT STORE_ID) AS STORES, COUNT(DISTINCT EMPLOYEE_ID) AS EMPLOYEES
FROM STORE_INFO A
LEFT JOIN EMPLOYEE B on A.CITY=B.CITY
GROUP BY 1;

SELECT A.ORDER_ID, C.TARGET_DELIVERY_DAYS
FROM ALL_ORDER A
JOIN ONLINE_ORDER B 
ON A.ORDER_ID=B.ORDER_ID
JOIN SHIPMENT C ON B.ORDER_ID=C.ORDER_ID;

SELECT A.MANUFACTURER_ID, A.MANUFACTURER_NAME, MAX(B.DISCOUNT) AS MAX_DISCOUNT
FROM MANUFACTURER A
JOIN PRODUCT B 
ON A.MANUFACTURER_ID = B.MANUFACTURER_ID
GROUP BY 1,2;